items/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^categories/$', views.list_categories, name='list_categories'),

    url(r'^categories/add/$', views.add_category, name='add_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_category, name='view_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_category, name='edit_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_category, name='delete_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.category_books, name='category_books'),

    url(r'^languages/$', views.list_languages, name='list_languages'),

    url(r'^languages/add/$', views.add_language, name='add_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_language, name='view_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_language, name='edit_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_language, name='delete_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.language_books, name='language_books'),

    url(r'^books/$', views.list_book_details, name='list_book_details'),

    url(r'^books/add/$', views.add_book_detail, name='add_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/$', views.view_book_detail, name='view_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/edit/$', views.edit_book_detail, name='edit_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/delete/$', views.delete_book_detail, name='delete_book_detail'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/add/$', views.add_book_copy, name='add_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/$', views.view_book_copy, name='view_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/edit/$', views.edit_book_copy, name='edit_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/delete/$', views.delete_book_copy,
        name='delete_book_copy'),

    url(r'^periodicals/$', views.list_periodicals, name='list_periodicals'),

    url(r'^periodicals/add/$', views.add_periodical, name='add_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/$', views.view_periodical, name='view_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/edit/$', views.edit_periodical, name='edit_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/delete/$', views.delete_periodical, name='delete_periodical'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/$', views.list_periodical_issues, name='list_periodical_issues'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/add/$', views.add_periodical_issue, name='add_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/$', views.view_periodical_issue,
        name='view_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/edit/$', views.edit_periodical_issue,
        name='edit_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/delete/$', views.delete_periodical_issue,
        name='delete_periodical_issue'),
]

livre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from index import views as index_views
from items import urls as items_urls
from accounts import urls as accounts_urls
from circulations import urls as circulations_urls
from search import urls as search_urls


urlpatterns = [
    url(r'^$', index_views.index, name='index'),

    url(r'^accounts/login/$', accounts_views.login_user, name='login'),

    url(r'^accounts/logout/$', auth_views.logout, {
        'template_name': 'accounts/logout.html',
    }, name='logout'),

    url(r'^accounts/register/$', accounts_views.register, name='register'),

    url(r'^accounts/password-change/$', auth_views.password_change, {
        'template_name': 'accounts/password-change.html',
    }, name='password_change'),

    url(r'^accounts/password-change-done/$', auth_views.password_change_done, {
        'template_name': 'accounts/password-change-done.html',
    }, name='password_change_done'),

    url(r'^accounts/password-reset/$', auth_views.password_reset, {
        'template_name': 'accounts/password-reset.html',
        'email_template_name': 'email/password-reset.html',
        'subject_template_name': 'email/password-reset-subject.html',
    }, name='password_reset'),

    url(r'^accounts/password-reset-done/$', auth_views.password_reset_done, {
        'template_name': 'accounts/password-reset-done.html',
    }, name='password_reset_done'),

    url(r'^accounts/password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {
        'template_name': 'accounts/password-reset-confirm.html',
    }, name='password_reset_confirm'),

    url(r'^accounts/password-reset-complete/$', auth_views.password_reset_complete, {
        'template_name': 'accounts/password-reset-complete.html',
    }, name='password_reset_complete'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^items/', include(items_urls, namespace='items')),

    url(r'^accounts/', include(accounts_urls, namespace='accounts')),

    url(r'^circulations/', include(circulations_urls, namespace='circulations')),

    url(r'^search/', include(search_urls, namespace='search')),
]

items/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.core.urlresolvers import reverse


BOOK_STATUS_CHOICES = (
    (1, 'Available'),
    (2, 'In Circulation'),
    (3, 'Temporarily Unavailable'),
    (4, 'Unavailable'),
    (5, 'Protected'),
    (6, 'Damaged'),
)


class Category(models.Model):
    """Item category model."""

    title = models.CharField(max_length=512)
    slug = models.SlugField(max_length=128, unique=True, db_index=True)
    description = models.TextField(blank=True, default='')
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User, related_name='category_updated_by')
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('items:view_category', kwargs={'slug': self.slug})


class Language(models.Model):
    """Language model"""

    name = models.CharField(max_length=512)
    short_code = models.CharField(max_length=8, db_index=True, unique=True)
    description = models.TextField(blank=True, default='')
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User, related_name='language_updated_by')
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('items:view_language', kwargs={'slug': self.short_code})


class BookDetail(models.Model):
    """Model to store book details."""

    title = models.CharField(max_length=1024)
    author = models.CharField(max_length=1024, default='Unknown')
    description = models.TextField(blank=True, default='')
    category = models.ForeignKey(Category)
    language = models.ForeignKey(Language)
    publisher = models.CharField(max_length=512, blank=True, default='')
    published_on = models.DateField(blank=True, null=True)
    pages = models.PositiveIntegerField(default=0, blank=True, null=True)
    ddc = models.CharField(max_length=1024, blank=True, default='')
    llcc = models.CharField(max_length=1024, blank=True, default='')
    isbn = models.CharField(max_length=1024, blank=True, default='')
    tags = models.CharField(max_length=1024, blank=True, null=True)
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User, related_name='book_detail_updated_by')
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('items:view_book_detail', kwargs={'id': self.id})

    def get_tags_string(self):
        return self.tags.capitalize()


class BookCopy(models.Model):
    """Model to store book copy details."""

    book_detail = models.ForeignKey(BookDetail)
    book_status = models.IntegerField(choices=BOOK_STATUS_CHOICES)
    remarks = models.TextField(blank=True, default='')
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User, related_name='book_copy_updated_by')
    updated_on = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('items:view_book_copy', kwargs={'book_id': self.book_detail.id, 'copy_id': self.id})


class Periodical(models.Model):
    """Model to store periodical data."""

    title = models.CharField(max_length=1024)
    description = models.TextField(blank=True, default='')
    category = models.ForeignKey(Category)
    language = models.ForeignKey(Language)
    publisher = models.CharField(max_length=512, blank=True, default='')
    tags = models.CharField(max_length=1024, blank=True, null=True)
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User, related_name='periodical_updated_by')
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('items:view_periodical', kwargs={'id': self.id})

    def get_tags_string(self):
        return self.tags.capitalize()


class PeriodicalIssue(models.Model):
    """Model to store periodical issues."""

    periodical = models.ForeignKey(Periodical)
    issue_status = models.IntegerField(choices=BOOK_STATUS_CHOICES)
    published_on = models.DateField(blank=True, null=True)
    volume = models.PositiveIntegerField(blank=True, null=True)
    issue = models.PositiveIntegerField(blank=True, null=True)
    remarks = models.TextField(blank=True, default='')
    tags = models.CharField(max_length=1024, blank=True, null=True)
    created_by = models.ForeignKey(User)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(User, related_name='periodical_issue_updated_by')
    updated_on = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('items:view_periodical_issue', kwargs={'periodical_id': self.periodical.id, 'issue_id': self.id})

    def get_tags_string(self):
        return self.tags.capitalize()

items/forms.py
from django import forms

from .models import Category, Language, BOOK_STATUS_CHOICES


# Trying to use Category and Language models before running migrations will result in errors.
# Try block is used to prevent those errors.
try:
    CATEGORY_CHOICES = [[x.slug, x.title] for x in Category.objects.all()]
    LANGUAGE_CHOICES = [[x.short_code, x.name] for x in Language.objects.all()]
except:
    CATEGORY_CHOICES = []
    LANGUAGE_CHOICES = []


class CategoryForm(forms.Form):
    title = forms.CharField(label='Title*:', max_length=500, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Title'
    }))
    slug = forms.SlugField(label='Slug*:', max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Slug',
    }))
    description = forms.CharField(label='Description:', max_length=4000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description',
    }), required=False)


class LanguageForm(forms.Form):
    name = forms.CharField(label='Name*:', max_length=500, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Name'
    }))
    short_code = forms.SlugField(label='Short code*:', max_length=8, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Short code',
    }))
    description = forms.CharField(label='Description:', max_length=4000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description',
    }), required=False)


class BookDetailForm(forms.Form):
    title = forms.CharField(label='Title*:', max_length=1000, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Title'
    }))
    author = forms.CharField(label='Author*:', max_length=1000, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Author'
    }))
    description = forms.CharField(label='Description:', max_length=10000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description',
    }), required=False)
    category = forms.ChoiceField(label='Category*:', choices=CATEGORY_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'required': 'required',
    }, choices=CATEGORY_CHOICES))
    language = forms.ChoiceField(label='Language*:', choices=LANGUAGE_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'required': 'required',
    }, choices=LANGUAGE_CHOICES))
    publisher = forms.CharField(label='Publisher:', max_length=500, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Publisher'
    }), required=False)
    published_on = forms.DateField(label='Published on:', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Published on'
    }), required=False)
    pages = forms.IntegerField(label='Pages:', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Pages',
    }), required=False)
    isbn = forms.CharField(label='ISBN:', max_length=1000, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ISBN',
    }), required=False)
    tags = forms.CharField(label='Tags:', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tags'
    }))


class BookCopyForm(forms.Form):
    book_status = forms.ChoiceField(label='Book status*:', widget=forms.Select(choices=BOOK_STATUS_CHOICES, attrs={
        'class': 'form-control',
    }), choices=BOOK_STATUS_CHOICES)
    remarks = forms.CharField(label='Description:', max_length=4000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Remarks',
    }), required=False)


class PeriodicalForm(forms.Form):
    title = forms.CharField(label='Title*:', max_length=1000, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Title'
    }))
    description = forms.CharField(label='Description:', max_length=10000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description',
    }), required=False)
    category = forms.ChoiceField(label='Category*:', choices=CATEGORY_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'required': 'required',
    }, choices=CATEGORY_CHOICES))
    language = forms.ChoiceField(label='Language*:', choices=LANGUAGE_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control',
        'required': 'required',
    }, choices=LANGUAGE_CHOICES))
    publisher = forms.CharField(label='Publisher:', max_length=500, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Publisher'
    }), required=False)
    tags = forms.CharField(label='Tags:', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tags'
    }))


class PeriodicalIssueForm(forms.Form):
    issue_status = forms.ChoiceField(label='Issue status*:', widget=forms.Select(choices=BOOK_STATUS_CHOICES, attrs={
        'class': 'form-control',
    }), choices=BOOK_STATUS_CHOICES)
    published_on = forms.DateField(label='Published on:', widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Published on'
    }), required=False)
    volume = forms.IntegerField(label='Volume:', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Volume',
    }))
    issue = forms.IntegerField(label='Issue:', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Issue',
    }))
    remarks = forms.CharField(label='Description:', max_length=4000, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Remarks',
    }), required=False)
    tags = forms.CharField(label='Tags:', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Tags'
    }))

items/templates/items/add-periodical-issue.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Add Issue of {{ periodical.title }} | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Add Issue of {{ periodical.title }}</h1>
</div>
{% include 'includes/message-alert.html' %}
<p>Fields marked with * are required.</p>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_issue_status">{{ form.issue_status.label }}</label>
        {% if form.issue_status.errors %}<p class="text-danger">{{ form.issue_status.errors.as_text }}</p>{% endif %}
        {{ form.issue_status }}
    </div>
    <div class="form-group">
        <label for="id_published_on">{{ form.published_on.label }}</label>
        {% if form.published_on.errors %}<p class="text-danger">{{ form.published_on.errors.as_text }}</p>{% endif %}
        {{ form.published_on }}
    </div>
    <div class="form-group">
        <label for="id_volume">{{ form.volume.label }}</label>
        {% if form.volume.errors %}<p class="text-danger">{{ form.volume.errors.as_text }}</p>{% endif %}
        {{ form.volume }}
    </div>
    <div class="form-group">
        <label for="id_issue">{{ form.issue.label }}</label>
        {% if form.issue.errors %}<p class="text-danger">{{ form.issue.errors.as_text }}</p>{% endif %}
        {{ form.issue }}
    </div>
    <div class="form-group">
        <label for="id_tags">{{ form.tags.label }}</label>
        {% if form.tags.errors %}<p class="text-danger">{{ form.tags.errors.as_text }}</p>{% endif %}
        {{ form.tags }}
    </div>
    <div class="form-group">
        <label for="id_remarks">{{ form.remarks.label }}</label>
        {% if form.remarks.errors %}<p class="text-danger">{{ form.remarks.errors.as_text }}</p>{% endif %}
        {{ form.remarks }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-default" href="{{ periodical.get_absolute_url }}">Cancel</a>
</form>
{% endblock content %}

items/templates/items/add-periodical.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Add Periodical | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Add New Periodical</h1>
</div>
{% include 'includes/message-alert.html' %}
<p>Fields marked with * are required.</p>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_title">{{ form.title.label }}</label>
        {% if form.title.errors %}<p class="text-danger">{{ form.title.errors.as_text }}</p>{% endif %}
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="id_description">{{ form.description.label }}</label>
        {% if form.description.errors %}<p class="text-danger">{{ form.description.errors.as_text }}</p>{% endif %}
        {{ form.description }}
    </div>
    <div class="form-group">
        <label for="id_category">{{ form.category.label }}</label>
        {% if form.category.errors %}<p class="text-danger">{{ form.category.errors.as_text }}</p>{% endif %}
        {{ form.category }}
    </div>
    <div class="form-group">
        <label for="id_language">{{ form.language.label }}</label>
        {% if form.language.errors %}<p class="text-danger">{{ form.language.errors.as_text }}</p>{% endif %}
        {{ form.language }}
    </div>
    <div class="form-group">
        <label for="id_publisher">{{ form.publisher.label }}</label>
        {% if form.publisher.errors %}<p class="text-danger">{{ form.publisher.errors.as_text }}</p>{% endif %}
        {{ form.publisher }}
    </div>
    <div class="form-group">
        <label for="id_tags">{{ form.tags.label }}</label>
        {% if form.tags.errors %}<p class="text-danger">{{ form.tags.errors.as_text }}</p>{% endif %}
        {{ form.tags }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-default" href="{% url 'items:list_periodicals' %}">Cancel</a>
</form>
{% endblock content %}

items/templates/items/edit-book-detail.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Edit {{ book_detail.title }} | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Edit {{ book_detail.title }}</h1>
</div>
{% include 'includes/message-alert.html' %}
<p>Fields marked with * are required.</p>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_title">{{ form.title.label }}</label>
        {% if form.title.errors %}<p class="text-danger">{{ form.title.errors.as_text }}</p>{% endif %}
        <input type="text" name="title" id="id_title" class="form-control" placeholder="Title" value="{{ book_detail.title }}" >
    </div>
    <div class="form-group">
        <label for="id_author">{{ form.author.label }}</label>
        {% if form.author.errors %}<p class="text-danger">{{ form.author.errors.as_text }}</p>{% endif %}
        <input type="text" name="author" id="id_author" class="form-control" placeholder="Author" value="{{ book_detail.author }}" >
    </div>
    <div class="form-group">
        <label for="id_description">{{ form.description.label }}</label>
        {% if form.description.errors %}<p class="text-danger">{{ form.description.errors.as_text }}</p>{% endif %}
        <textarea placeholder="Description" id="id_description" class="form-control" name="description" rows="8">{{ book_detail.description }}</textarea>
    </div>
    <div class="form-group">
        <label for="id_category">{{ form.category.label }}</label>
        {% if form.category.errors %}<p class="text-danger">{{ form.category.errors.as_text }}</p>{% endif %}
        {{ form.category }}
    </div>
    <div class="form-group">
        <label for="id_language">{{ form.language.label }}</label>
        {% if form.language.errors %}<p class="text-danger">{{ form.language.errors.as_text }}</p>{% endif %}
        {{ form.language }}
    </div>
    <div class="form-group">
        <label for="id_publisher">{{ form.publisher.label }}</label>
        {% if form.publisher.errors %}<p class="text-danger">{{ form.publisher.errors.as_text }}</p>{% endif %}
        <input type="text" name="publisher" id="id_publisher" class="form-control" placeholder="Publisher" value="{{ book_detail.publisher }}" >
    </div>
    <div class="form-group">
        <label for="id_published_on">{{ form.published_on.label }}</label>
        {% if form.published_on.errors %}<p class="text-danger">{{ form.published_on.errors.as_text }}</p>{% endif %}
        <input type="text" name="published_on" id="id_published_on" class="form-control" placeholder="Published on" value="{% if book_detail.published_on %}{{ book_detail.published_on |date:'Y-m-d' }}{% endif %}" >
    </div>
    <div class="form-group">
        <label for="id_pages">{{ form.pages.label }}</label>
        {% if form.pages.errors %}<p class="text-danger">{{ form.pages.errors.as_text }}</p>{% endif %}
        <input type="text" name="pages" id="id_pages" class="form-control" placeholder="Pages" value="{{ book_detail.pages }}" >
    </div>
    <div class="form-group">
        <label for="id_isbn">{{ form.isbn.label }}</label>
        {% if form.isbn.errors %}<p class="text-danger">{{ form.isbn.errors.as_text }}</p>{% endif %}
        <input type="text" name="isbn" id="id_isbn" class="form-control" placeholder="ISBN" value="{{ book_detail.isbn }}" >
    </div>
    <div class="form-group">
        <label for="id_tags">{{ form.tags.label }}</label>
        {{ form.tags }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-default" href="{% url 'items:list_book_details' %}">Cancel</a>
</form>
{% endblock content %}

{% block footer %}
<script>
    $(function() {
        $('#id_category').val('{{ book_detail.category.slug }}');
        $('#id_language').val('{{ book_detail.language.short_code }}');
        $('#id_tags').val('{{ book_detail.get_tags_string }}');
    });
</script>
{% endblock footer %}

items/templates/items/edit-periodical-issue.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Edit Issue of {{ periodical.title }} | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Edit Issue of {{ periodical.title }}</h1>
</div>
{% include 'includes/message-alert.html' %}
<p>Fields marked with * are required.</p>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_issue_status">{{ form.issue_status.label }}</label>
        {% if form.issue_status.errors %}<p class="text-danger">{{ form.issue_status.errors.as_text }}</p>{% endif %}
        {{ form.issue_status }}
    </div>
    <div class="form-group">
        <label for="id_published_on">{{ form.published_on.label }}</label>
        {% if form.published_on.errors %}<p class="text-danger">{{ form.published_on.errors.as_text }}</p>{% endif %}
        {{ form.published_on }}
    </div>
    <div class="form-group">
        <label for="id_volume">{{ form.volume.label }}</label>
        {% if form.volume.errors %}<p class="text-danger">{{ form.volume.errors.as_text }}</p>{% endif %}
        {{ form.volume }}
    </div>
    <div class="form-group">
        <label for="id_issue">{{ form.issue.label }}</label>
        {% if form.issue.errors %}<p class="text-danger">{{ form.issue.errors.as_text }}</p>{% endif %}
        {{ form.issue }}
    </div>
    <div class="form-group">
        <label for="id_tags">{{ form.tags.label }}</label>
        {% if form.tags.errors %}<p class="text-danger">{{ form.tags.errors.as_text }}</p>{% endif %}
        {{ form.tags }}
    </div>
    <div class="form-group">
        <label for="id_remarks">{{ form.remarks.label }}</label>
        {% if form.remarks.errors %}<p class="text-danger">{{ form.remarks.errors.as_text }}</p>{% endif %}
        {{ form.remarks }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-default" href="{{ periodical.get_absolute_url }}">Cancel</a>
</form>
{% endblock content %}

{% block footer %}
<script>
    $(function() {
        $('#id_issue_status').val('{{ periodical_issue.issue_status }}');
        $('#id_published_on').val('{{ periodical_issue.published_on |date:'Y-m-d' }}');
        $('#id_volume').val('{{ periodical_issue.volume }}');
        $('#id_issue').val('{{ periodical_issue.issue }}');
        $('#id_remarks').val('{{ periodical_issue.remarks }}');
        $('#id_tags').val('{{ periodical_issue.get_tags_string }}');
    });
</script>
{% endblock footer %}