accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

    url(r'^users/$', views.list_users, name='list_users'),

    url(r'^users/add/$', views.add_user, name='add_user'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/$', views.view_user_profile, name='view_user_profile'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/remove/$', views.remove_user, name='remove_user'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/change-staff-status/$', views.change_staff_status,
        name='change_staff_status'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/change-admin-status/$', views.change_admin_status,
        name='change_admin_status'),

    url(r'^my-books/$', views.my_books, name='my_books'),
]

circulations/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.circulations, name='circulations'),

    url(r'^issue/$', views.add_circulation, name='add_circulation'),

    url(r'^issue/confirm/$', views.add_circulation_confirm, name='add_circulation_confirm'),

    url(r'^return/$', views.return_circulation, name='return_circulation'),

    url(r'^return/confirm/$', views.return_circulation_confirm, name='return_circulation_confirm'),
]

items/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^categories/$', views.list_categories, name='list_categories'),

    url(r'^categories/add/$', views.add_category, name='add_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_category, name='view_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_category, name='edit_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_category, name='delete_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.category_books, name='category_books'),

    url(r'^languages/$', views.list_languages, name='list_languages'),

    url(r'^languages/add/$', views.add_language, name='add_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_language, name='view_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_language, name='edit_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_language, name='delete_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.language_books, name='language_books'),

    url(r'^books/$', views.list_book_details, name='list_book_details'),

    url(r'^books/add/$', views.add_book_detail, name='add_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/$', views.view_book_detail, name='view_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/edit/$', views.edit_book_detail, name='edit_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/delete/$', views.delete_book_detail, name='delete_book_detail'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/add/$', views.add_book_copy, name='add_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/$', views.view_book_copy, name='view_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/edit/$', views.edit_book_copy, name='edit_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/delete/$', views.delete_book_copy,
        name='delete_book_copy'),

    url(r'^periodicals/$', views.list_periodicals, name='list_periodicals'),

    url(r'^periodicals/add/$', views.add_periodical, name='add_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/$', views.view_periodical, name='view_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/edit/$', views.edit_periodical, name='edit_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/delete/$', views.delete_periodical, name='delete_periodical'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/$', views.list_periodical_issues, name='list_periodical_issues'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/add/$', views.add_periodical_issue, name='add_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/$', views.view_periodical_issue,
        name='view_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/edit/$', views.edit_periodical_issue,
        name='edit_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/delete/$', views.delete_periodical_issue,
        name='delete_periodical_issue'),
]

livre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from index import views as index_views
from items import urls as items_urls
from accounts import urls as accounts_urls
from circulations import urls as circulations_urls
from search import urls as search_urls


urlpatterns = [
    url(r'^$', index_views.index, name='index'),

    url(r'^accounts/login/$', accounts_views.login_user, name='login'),

    url(r'^accounts/logout/$', auth_views.logout, {
        'template_name': 'accounts/logout.html',
    }, name='logout'),

    url(r'^accounts/register/$', accounts_views.register, name='register'),

    url(r'^accounts/password-change/$', auth_views.password_change, {
        'template_name': 'accounts/password-change.html',
    }, name='password_change'),

    url(r'^accounts/password-change-done/$', auth_views.password_change_done, {
        'template_name': 'accounts/password-change-done.html',
    }, name='password_change_done'),

    url(r'^accounts/password-reset/$', auth_views.password_reset, {
        'template_name': 'accounts/password-reset.html',
        'email_template_name': 'email/password-reset.html',
        'subject_template_name': 'email/password-reset-subject.html',
    }, name='password_reset'),

    url(r'^accounts/password-reset-done/$', auth_views.password_reset_done, {
        'template_name': 'accounts/password-reset-done.html',
    }, name='password_reset_done'),

    url(r'^accounts/password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {
        'template_name': 'accounts/password-reset-confirm.html',
    }, name='password_reset_confirm'),

    url(r'^accounts/password-reset-complete/$', auth_views.password_reset_complete, {
        'template_name': 'accounts/password-reset-complete.html',
    }, name='password_reset_complete'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^items/', include(items_urls, namespace='items')),

    url(r'^accounts/', include(accounts_urls, namespace='accounts')),

    url(r'^circulations/', include(circulations_urls, namespace='circulations')),

    url(r'^search/', include(search_urls, namespace='search')),
]

templates/layouts/site-layout.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %}
    {% endblock head %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
<!-- Main menu -->
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid menu">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
                    <a class="navbar-brand" href="/">{{ SITE_CONFIG.SITE_NAME }}</a>
				</div>
				<div class="collapse navbar-collapse" id="main-menu">
					<ul class="nav navbar-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Collections <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'items:list_categories' %}">Categories</a></li>
								<li><a href="{% url 'items:list_languages' %}">Languages</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Books <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'items:list_book_details' %}">Books</a></li>
								<li><a href="{% url 'items:list_periodicals' %}">Periodicals</a></li>
							</ul>
						</li>
						{% if user.is_authenticated %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'accounts:my_books' %}">My Books</a></li>
								<li><a href="{% url 'accounts:profile' %}">Profile</a></li>
								<li><a href="{% url 'password_change' %}">Change password</a></li>
								<li><a href="{% url 'logout' %}">Logout</a></li>
							</ul>
						</li>
						{% else %}
						<li><a href="{% url 'login' %}">Log In</a></li>
						{% endif %}
						{% if user.is_staff %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Manage <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'circulations:circulations' %}">Circulations</a></li>
								<li><a href="{% url 'accounts:list_users' %}">Users</a></li>
							</ul>
						</li>
						{% endif %}
                    </ul>

					<form class="navbar-form navbar-right" role="search" action="/search/books/">
						<div class="form-group">
							<input type="search" name="term" class="form-control" placeholder="Search" />
						</div>
						<button class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
					</form>
				</div>
			</div>
		</div>
	</nav><!-- end main menu -->

    <!-- content body -->
	<div class="container">
		<div class="row">
			<!-- main content -->
			<div class="col-lg-8 col-md-8">
				<p>&nbsp;</p>
				<p>&nbsp;</p>
				<p class="hidden-xs hidden-sm">&nbsp;</p>
			{% block content %}
			{% endblock content %}
			</div><!-- end main content -->
			<!-- sidebar -->
			<div class="col-lg-4 col-md-4">
			<p class="hidden-xs hidden-sm">&nbsp;</p>
			<p class="hidden-xs hidden-sm">&nbsp;</p>
			<p class="hidden-xs hidden-sm">&nbsp;</p>
			{% block sidebar %}
			{% endblock sidebar %}
			</div><!-- end sidebar -->
		</div>
	</div><!-- end content body -->

	<!-- footer -->
	<div class="container">
		<hr class="sepr" />
		<div class="row">
			<div class="col-lg-4 col-md-4">
				<ul class="list-unstyled">
				</ul>
			</div>
			<div class="col-lg-4 col-md-4">
				<ul class="list-unstyled">
				</ul>
			</div>
			<div class="col-lg-4 col-md-4">
				<ul class="list-unstyled">
				</ul>
			</div>
		</div>
		<p class="text-center">&copy; {% now 'Y' %}</p>
	</div><!-- end footer -->

    <script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block footer %}
    {% endblock footer %}
</body>
</html>