accounts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),

    url(r'^users/$', views.list_users, name='list_users'),

    url(r'^users/add/$', views.add_user, name='add_user'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/$', views.view_user_profile, name='view_user_profile'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/remove/$', views.remove_user, name='remove_user'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/change-staff-status/$', views.change_staff_status,
        name='change_staff_status'),

    url(r'^users/(?P<username>[-a-zA-Z0-9_]+)/change-admin-status/$', views.change_admin_status,
        name='change_admin_status'),

    url(r'^my-books/$', views.my_books, name='my_books'),
]

items/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^categories/$', views.list_categories, name='list_categories'),

    url(r'^categories/add/$', views.add_category, name='add_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_category, name='view_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_category, name='edit_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_category, name='delete_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.category_books, name='category_books'),

    url(r'^languages/$', views.list_languages, name='list_languages'),

    url(r'^languages/add/$', views.add_language, name='add_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_language, name='view_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_language, name='edit_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_language, name='delete_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.language_books, name='language_books'),

    url(r'^books/$', views.list_book_details, name='list_book_details'),

    url(r'^books/add/$', views.add_book_detail, name='add_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/$', views.view_book_detail, name='view_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/edit/$', views.edit_book_detail, name='edit_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/delete/$', views.delete_book_detail, name='delete_book_detail'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/add/$', views.add_book_copy, name='add_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/$', views.view_book_copy, name='view_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/edit/$', views.edit_book_copy, name='edit_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/delete/$', views.delete_book_copy,
        name='delete_book_copy'),

    url(r'^periodicals/$', views.list_periodicals, name='list_periodicals'),

    url(r'^periodicals/add/$', views.add_periodical, name='add_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/$', views.view_periodical, name='view_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/edit/$', views.edit_periodical, name='edit_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/delete/$', views.delete_periodical, name='delete_periodical'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/$', views.list_periodical_issues, name='list_periodical_issues'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/add/$', views.add_periodical_issue, name='add_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/$', views.view_periodical_issue,
        name='view_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/edit/$', views.edit_periodical_issue,
        name='edit_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/delete/$', views.delete_periodical_issue,
        name='delete_periodical_issue'),
]

livre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from index import views as index_views
from items import urls as items_urls
from accounts import urls as accounts_urls
from circulations import urls as circulations_urls
from search import urls as search_urls


urlpatterns = [
    url(r'^$', index_views.index, name='index'),

    url(r'^accounts/login/$', accounts_views.login_user, name='login'),

    url(r'^accounts/logout/$', auth_views.logout, {
        'template_name': 'accounts/logout.html',
    }, name='logout'),

    url(r'^accounts/register/$', accounts_views.register, name='register'),

    url(r'^accounts/password-change/$', auth_views.password_change, {
        'template_name': 'accounts/password-change.html',
    }, name='password_change'),

    url(r'^accounts/password-change-done/$', auth_views.password_change_done, {
        'template_name': 'accounts/password-change-done.html',
    }, name='password_change_done'),

    url(r'^accounts/password-reset/$', auth_views.password_reset, {
        'template_name': 'accounts/password-reset.html',
        'email_template_name': 'email/password-reset.html',
        'subject_template_name': 'email/password-reset-subject.html',
    }, name='password_reset'),

    url(r'^accounts/password-reset-done/$', auth_views.password_reset_done, {
        'template_name': 'accounts/password-reset-done.html',
    }, name='password_reset_done'),

    url(r'^accounts/password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {
        'template_name': 'accounts/password-reset-confirm.html',
    }, name='password_reset_confirm'),

    url(r'^accounts/password-reset-complete/$', auth_views.password_reset_complete, {
        'template_name': 'accounts/password-reset-complete.html',
    }, name='password_reset_complete'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^items/', include(items_urls, namespace='items')),

    url(r'^accounts/', include(accounts_urls, namespace='accounts')),

    url(r'^circulations/', include(circulations_urls, namespace='circulations')),

    url(r'^search/', include(search_urls, namespace='search')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


GENDER_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Not specified', 'Not Specified'),
)

IS_ACTIVE_CHOICES = (
    (True, 'Active'),
    (False, 'Inactive'),
)


class UserProfile(models.Model):
    """Model to add a profile to user."""

    user = models.OneToOneField(User)
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES, default='Not specified')
    birthday = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=24, blank=True, null=True)
    city = models.CharField(max_length=150, blank=True, null=True)
    state = models.CharField(max_length=150, blank=True, null=True)
    country = models.CharField(max_length=150, blank=True, null=True)
    zip_code = models.CharField(max_length=8, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms

from .models import GENDER_CHOICES


class RegisterForm(forms.Form):
    first_name = forms.CharField(label='First name:', max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'First name'
    }))
    last_name = forms.CharField(label='Last name:', max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Last name'
    }))
    username = forms.SlugField(label='Username:', max_length=16, min_length=4, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Username'
    }))
    email = forms.EmailField(label='Email:', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
    }), required=False)
    password = forms.CharField(label='Password:', max_length=32, min_length=6, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'password',
        'required': 'required',
    }))
    confirm_password = forms.CharField(label='Retype password:', max_length=32, min_length=6, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'password', 'required': 'required',}
    ))


class LoginForm(forms.Form):
    """ Form to handle login.
    """

    username = forms.SlugField(label='Username:', max_length=32, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Username', 'required': 'required', }))
    password = forms.CharField(label='Password:', max_length=64, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Password', 'required': 'required', }))


class ProfileForm(forms.Form):

    first_name = forms.CharField(label='First name*:', max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'First name', 'required': 'required', }))
    last_name = forms.CharField(label='Last name*:', max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Last name', 'required': 'required', }))
    gender = forms.ChoiceField(label='Gender', choices=GENDER_CHOICES, widget=forms.Select(attrs={
        'class': 'form-control'}, choices=GENDER_CHOICES))
    email = forms.EmailField(label='Email:', required=False, widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Email', }))
    birthday = forms.DateField(label='Birthday (YYYY-MM-DD):', required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Birthday', }))
    phone = forms.CharField(label='Phone:', max_length=20, min_length=6, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Phone', }))
    city = forms.CharField(label='City:', max_length=150, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'City', }))
    state = forms.CharField(label='State:', max_length=150, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'State', }))
    country = forms.CharField(label='Country:', max_length=150, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Country', }))
    zip_code = forms.CharField(label='Zip code:', max_length=8, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Zip code', }))


class AddUserForm(forms.Form):
    first_name = forms.CharField(label='First name:', max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'First name', 'required': 'required', }))
    last_name = forms.CharField(label='Last name:', max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Last name', 'required': 'required', }))
    username = forms.SlugField(label='Username:', max_length=32, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Username', 'required': 'required', }))
    password = forms.CharField(label='Password:', min_length=6, max_length=64, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Password', 'required': 'required', }))


class RemoveUserForm(forms.Form):
    username = forms.SlugField(label='Username:', max_length=32, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Username', 'required': 'required', }))

accounts/templates/accounts/add-user.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Add User | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Add User</h1>
</div>
{% include 'includes/message-alert.html' %}
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_first_name">{{ form.first_name.label }}</label>
        {% if form.first_name.errors %}<p class="text-danger">{{ form.first_name.errors.as_text }}</p>{% endif %}
        {{ form.first_name }}
    </div>
    <div class="form-group">
        <label for="id_last_name">{{ form.last_name.label }}</label>
        {% if form.last_name.errors %}<p class="text-danger">{{ form.last_name.errors.as_text }}</p>{% endif %}
        {{ form.last_name }}
    </div>
    <div class="form-group">
        <label for="id_username">{{ form.username.label }}</label>
        {% if form.username.errors %}<p class="text-danger">{{ form.username.errors.as_text }}</p>{% endif %}
        {{ form.username }}
    </div>
    <div class="form-group">
        <label for="id_password">{{ form.password.label }}</label>
        {% if form.password.errors %}<p class="text-danger">{{ form.password.errors.as_text }}</p>{% endif %}
        {{ form.password }}
    </div>
    <button type="submit" class="btn btn-primary">Add User</button>
</form>
{% endblock content %}

accounts/templates/accounts/edit-profile.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Edit Profile | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block  content %}
<div class="page-header">
    <h1>Edit Profile</h1>
</div>
<form action="" method="post">
    {% include 'includes/message-alert.html' %}
    {% csrf_token %}
    <div class="form-group">
        <label for="id_first_name">{{ form.first_name.label }}</label>
        {% if form.first_name.errors %}<p>{{ form.first_name.errors.as_text }}</p>{% endif %}
        {{ form.first_name }}
    </div>
    <div class="form-group">
        <label for="id_last_name">{{ form.last_name.label }}</label>
        {% if form.last_name.errors %}<p>{{ form.last_name.errors.as_text }}</p>{% endif %}
        {{ form.last_name }}
    </div>
    <div class="form-group">
        <label for="id_email">{{ form.email.label }}</label>
        {% if form.email.errors %}<p>{{ form.email.errors.as_text }}</p>{% endif %}
        {{ form.email }}
    </div>
    <div class="form-group">
        <label for="id_gender">{{ form.gender.label }}</label>
        {% if form.gender.errors %}<p>{{ form.gender.errors.as_text }}</p>{% endif %}
        {{ form.gender }}
    </div>
    <div class="form-group">
        <label for="id_birthday">{{ form.birthday.label }}</label>
        {% if form.birthday.errors %}<p>{{ form.birthday.errors.as_text }}</p>{% endif %}
        {{ form.birthday }}
    </div>
    <div class="form-group">
        <label for="id_phone">{{ form.phone.label }}</label>
        {% if form.phone.errors %}<p>{{ form.phone.errors.as_text }}</p>{% endif %}
        {{ form.phone }}
    </div>
    <div class="form-group">
        <label for="id_city">{{ form.city.label }}</label>
        {% if form.city.errors %}<p>{{ form.city.errors.as_text }}</p>{% endif %}
        {{ form.city }}
    </div>
    <div class="form-group">
        <label for="id_state">{{ form.state.label }}</label>
        {% if form.state.errors %}<p>{{ form.state.errors.as_text }}</p>{% endif %}
        {{ form.state }}
    </div>
    <div class="form-group">
        <label for="id_country">{{ form.country.label }}</label>
        {% if form.country.errors %}<p>{{ form.country.errors.as_text }}</p>{% endif %}
        {{ form.country }}
    </div>
    <div class="form-group">
        <label for="id_zip_code">{{ form.zip_code.label }}</label>
        {% if form.zip_code.errors %}<p>{{ form.zip_code.errors.as_text }}</p>{% endif %}
        {{ form.zip_code }}
    </div>
    <button type="submit" class="btn btn-primary">Update Profile</button>
</form>
{% endblock content %}

{% block footer %}
<script>
    $(function() {
        $('#id_first_name').val('{{ user.first_name }}');
        $('#id_last_name').val('{{ user.last_name }}');
        $('#id_email').val('{{ user.email }}');
        $('#id_gender').val('{{ user_profile.gender }}');
        $('#id_birthday').val('{{ user_profile.birthday |date:'Y-m-d' }}');
        $('#id_phone').val('{{ user_profile.phone }}');
        $('#id_city').val('{{ user_profile.city }}');
        $('#id_state').val('{{ user_profile.state }}');
        $('#id_country').val('{{ user_profile.country }}');
        $('#id_zip_code').val('{{ user_profile.zip_code }}');
    });
</script>
{% endblock footer %}

accounts/templates/accounts/list-users.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Users | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Users</h1>
</div>
{% include 'includes/message-alert.html' %}
<p><a class="btn btn-primary btn-sm" href="{% url 'accounts:add_user' %}"><span class="glyphicon glyphicon-plus"></span> Add User</a></p>
<table class="table table-hover table-striped table-bordered">
    <tr>
        <th>#</th>
        <td>Name</td>
        <td>Username</td>
        <td>Date Joined</td>
    </tr>
    {% for u in users %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'accounts:view_user_profile' u.username %}">{{ u.get_full_name }}</a></td>
        <td><a href="{% url 'accounts:view_user_profile' u.username %}">{{ u.username }}</a></td>
        <td>{{ u.date_joined |date:'d F Y' }}</td>
    </tr>
    {% endfor %}
</table>
{% if users.has_previous or users.has_next %}
<nav>
    <ul class="pager">
        {% if users.has_previous %}<li class="previous"><a href="{% url 'accounts:list_users' %}?page={{ users.previous_page_number }}"><span aria-hidden="true">&larr;</span> Previous</a>{% endif %}
        {% if users.has_next %}<li class="next"><a href="{% url 'accounts:list_users' %}?page={{ users.next_page_number }}">Next <span aria-hidden="true">&rarr;</span></a>{% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Log In | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="text-primary text-center">Log In</h1>
    </div>
    <div class="panel-body">
        {% include 'includes/message-alert.html' %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">{{ form.username.label }}</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="password">{{ form.password.label }}</label>
                {{ form.password }}
            </div>
            <p><a href="{% url 'password_reset' %}">Forgot Password?</a></p>
            <button type="submit" class="btn btn-primary">Log In</button>
            <a href="{% url 'register' %}" class="btn btn-default">Register New Account</a>
        </form>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Logged Out | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1 class="heading">Logged Out</h1>
</div>
<p>You are now logged out. <a href="{% url 'login' %}">Click here</a> to log in again.</p>
{% endblock content %}

accounts/templates/accounts/my-books.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>My Books | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>My Books</h1>
</div>
{% if circulations %}
<table class="table table-hover table-striped table-bordered">
    <tr>
        <th>ID</th>
        <th>Book</th>
        <th>Status</th>
        <th>Issued on</th>
        <th>Due date</th>
        <th>Returned on</th>
    </tr>
    {% for circulation in circulations %}
    <tr>
        <td>{{ circulation.id }}</td>
        <td><a href="{{ circulation.book_copy.get_absolute_url }}">{{ circulation.book_copy.book_detail.title }}</a> </td>
        <td>{{ circulation.get_status }}</td>
        <td>{{ circulation.issued_on |date:'d F Y' }}</td>
        <td>{{ circulation.due_date |date:'d F Y' }}</td>
        <td>{{ circulation.returned_on |date:'d F Y' }}</td>
    </tr>
    {% endfor %}
</table>
{% if circulations.has_previous or circulations.has_next %}
<nav>
    <ul class="pager">
        {% if circulations.has_previous %}<li class="previous"><a href="{% url 'accounts:my_books' %}?page={{ circulations.previous_page_number }}&filte={{ filter }}"><span aria-hidden="true">&larr;</span> Previous</a>{% endif %}
        {% if circulations.has_next %}<li class="next"><a href="{% url 'accounts:my_books' %}?page={{ circulations.next_page_number }}&filte={{ filter }}">Next <span aria-hidden="true">&rarr;</span></a>{% endif %}
    </ul>
</nav>
{% endif %}
{% else %}
<p>There are no books.</p>
{% endif %}
{% endblock content %}

accounts/templates/accounts/password-change-done.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Password Changed | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Password Changed</h1>
</div>
<p>You have successfully changed your password.</p>
{% endblock content %}

accounts/templates/accounts/password-reset.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Password Reset | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Password Reset</h1>
</div>
<p>Please enter the email associated with your account. If you forgot the email or you do not have an email associated with your account, please contact administrators.</p>
<form method="post" action="">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_email">{{ form.email.label_tag }}</label>
        {{ form.email }}
    </div>
    <button type="submit" class="btn btn-primary">Reset Password</button>
</form>
{% endblock content %}

{% block footer %}
<script>
    $(function(){
        $('input').addClass('form-control');
    });
</script>
{% endblock footer %}

accounts/templates/accounts/profile.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Profile | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>{{ user.get_full_name }}</h1>
</div>
<img src="http://www.gravatar.com/avatar/{{ gravathar_hash }}" class="img-thumbnail profile-pic profile-pic-md" />
<table class="table table-striped">
    <tr>
        <td>First name</td>
        <td>: {{ user.first_name }}</td>
    </tr>
    <tr>
        <td>Last name</td>
        <td>: {{ user.last_name }}</td>
    </tr>
    <tr>
        <td>Gender</td>
        <td>: {{ user_profile.get_gender_display }}</td>
    </tr>
    <tr>
        <td>Birthday</td>
        <td>: {{ user_profile.birthday }}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>: {{ user.email }}</td>
    </tr>
    <tr>
        <td>Phone</td>
        <td>: {{ user_profile.phone }}</td>
    </tr>
    <tr>
        <td>City</td>
        <td>: {{ user_profile.city }}</td>
    </tr><tr>
        <td>State</td>
        <td>: {{ user_profile.state }}</td>
    </tr><tr>
        <td>Country</td>
        <td>: {{ user_profile.country }}</td>
    </tr>
    <tr>
        <td>Zipcode</td>
        <td>: {{ user_profile.zipcode }}</td>
    </tr>
</table>
<p><a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">Edit Profile</a></p>
{% endblock content %}

accounts/templates/accounts/remove-user.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Remove {{ user_detail.get_full_name }} | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>Remove {{ user_detail.get_full_name }}</h1>
</div>
{% include 'includes/message-alert.html' %}
<p>Do you really want to remove this user? All data associated with this user will be deleted. Please enter the username of this user({{ user_detail.username }}) to confirm deletion.</p>
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.username }}
    </div>
    <button type="submit" class="btn btn-primary">Confirm</button>
    <a href="{% url 'accounts:list_users' %}" class="btn btn-default">Cancel</a>
</form>
{% endblock content %}

accounts/templates/accounts/view-user-profile.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>{{ user_detail.get_full_name }} - Profile | {{ SITE_CONFIG.SITE_NAME }}</title>
{% endblock head %}

{% block content %}
<div class="page-header">
    <h1>{{ user_detail.get_full_name }}</h1>
</div>
{% include 'includes/message-alert.html' %}
<img src="http://www.gravatar.com/avatar/{{ gravathar_hash }}" class="img-thumbnail profile-pic profile-pic-md" />
<table class="table table-striped">
    <tr>
        <td>First name</td>
        <td>: {{ user_detail.first_name }}</td>
    </tr>
    <tr>
        <td>Last name</td>
        <td>: {{ user_detail.last_name }}</td>
    </tr>
    <tr>
        <td>Gender</td>
        <td>: {{ user_profile.get_gender_display }}</td>
    </tr>
    <tr>
        <td>Birthday</td>
        <td>: {{ user_profile.birthday }}</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>: {{ user_detail.email }}</td>
    </tr>
    <tr>
        <td>Phone</td>
        <td>: {{ user_profile.phone }}</td>
    </tr>
    <tr>
        <td>City</td>
        <td>: {{ user_profile.city }}</td>
    </tr><tr>
        <td>State</td>
        <td>: {{ user_profile.state }}</td>
    </tr><tr>
        <td>Country</td>
        <td>: {{ user_profile.country }}</td>
    </tr>
    <tr>
        <td>Zipcode</td>
        <td>: {{ user_profile.zipcode }}</td>
    </tr>
</table>
<p>
    <a class="btn btn-danger btn-sm" href="{% url 'accounts:remove_user' user_detail.username %}">Remove User</a>
    {% if is_admin %}<a class="btn btn-primary btn-sm" href="{% url 'accounts:change_staff_status' user_detail.username %}">{% if user_detail.is_staff %}Remove from staffs{% else %}Add to staffs{% endif %}</a>
    <a class="btn btn-primary btn-sm" href="{% url 'accounts:change_admin_status' user_detail.username %}">{% if user_detail.is_superuser %}Remove from admins{% else %}Add to admins{% endif %}</a>{% endif %}
</p>
{% endblock content %}