circulations/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.circulations, name='circulations'),

    url(r'^issue/$', views.add_circulation, name='add_circulation'),

    url(r'^issue/confirm/$', views.add_circulation_confirm, name='add_circulation_confirm'),

    url(r'^return/$', views.return_circulation, name='return_circulation'),

    url(r'^return/confirm/$', views.return_circulation_confirm, name='return_circulation_confirm'),
]

items/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^categories/$', views.list_categories, name='list_categories'),

    url(r'^categories/add/$', views.add_category, name='add_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_category, name='view_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_category, name='edit_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_category, name='delete_category'),

    url(r'^categories/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.category_books, name='category_books'),

    url(r'^languages/$', views.list_languages, name='list_languages'),

    url(r'^languages/add/$', views.add_language, name='add_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/$', views.view_language, name='view_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/edit/$', views.edit_language, name='edit_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/delete/$', views.delete_language, name='delete_language'),

    url(r'^languages/(?P<slug>[-a-zA-Z0-9_]+)/books/$', views.language_books, name='language_books'),

    url(r'^books/$', views.list_book_details, name='list_book_details'),

    url(r'^books/add/$', views.add_book_detail, name='add_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/$', views.view_book_detail, name='view_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/edit/$', views.edit_book_detail, name='edit_book_detail'),

    url(r'^books/(?P<id>[0-9]+)/delete/$', views.delete_book_detail, name='delete_book_detail'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/add/$', views.add_book_copy, name='add_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/$', views.view_book_copy, name='view_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/edit/$', views.edit_book_copy, name='edit_book_copy'),

    url(r'^books/(?P<book_id>[0-9]+)/copy/(?P<copy_id>[0-9]+)/delete/$', views.delete_book_copy,
        name='delete_book_copy'),

    url(r'^periodicals/$', views.list_periodicals, name='list_periodicals'),

    url(r'^periodicals/add/$', views.add_periodical, name='add_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/$', views.view_periodical, name='view_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/edit/$', views.edit_periodical, name='edit_periodical'),

    url(r'^periodicals/(?P<id>[0-9]+)/delete/$', views.delete_periodical, name='delete_periodical'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/$', views.list_periodical_issues, name='list_periodical_issues'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/add/$', views.add_periodical_issue, name='add_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/$', views.view_periodical_issue,
        name='view_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/edit/$', views.edit_periodical_issue,
        name='edit_periodical_issue'),

    url(r'^periodicals/(?P<periodical_id>[0-9]+)/issues/(?P<issue_id>[0-9]+)/delete/$', views.delete_periodical_issue,
        name='delete_periodical_issue'),
]

livre/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from index import views as index_views
from items import urls as items_urls
from accounts import urls as accounts_urls
from circulations import urls as circulations_urls
from search import urls as search_urls


urlpatterns = [
    url(r'^$', index_views.index, name='index'),

    url(r'^accounts/login/$', accounts_views.login_user, name='login'),

    url(r'^accounts/logout/$', auth_views.logout, {
        'template_name': 'accounts/logout.html',
    }, name='logout'),

    url(r'^accounts/register/$', accounts_views.register, name='register'),

    url(r'^accounts/password-change/$', auth_views.password_change, {
        'template_name': 'accounts/password-change.html',
    }, name='password_change'),

    url(r'^accounts/password-change-done/$', auth_views.password_change_done, {
        'template_name': 'accounts/password-change-done.html',
    }, name='password_change_done'),

    url(r'^accounts/password-reset/$', auth_views.password_reset, {
        'template_name': 'accounts/password-reset.html',
        'email_template_name': 'email/password-reset.html',
        'subject_template_name': 'email/password-reset-subject.html',
    }, name='password_reset'),

    url(r'^accounts/password-reset-done/$', auth_views.password_reset_done, {
        'template_name': 'accounts/password-reset-done.html',
    }, name='password_reset_done'),

    url(r'^accounts/password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm, {
        'template_name': 'accounts/password-reset-confirm.html',
    }, name='password_reset_confirm'),

    url(r'^accounts/password-reset-complete/$', auth_views.password_reset_complete, {
        'template_name': 'accounts/password-reset-complete.html',
    }, name='password_reset_complete'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^items/', include(items_urls, namespace='items')),

    url(r'^accounts/', include(accounts_urls, namespace='accounts')),

    url(r'^circulations/', include(circulations_urls, namespace='circulations')),

    url(r'^search/', include(search_urls, namespace='search')),
]

index/templates/index/index.html
{% extends 'layouts/site-layout.html' %}

{% block head %}
<title>Home | {{ SITE_CONFIG.SITE_NAME }}</title>
<meta name="description" content="{{ SITE_CONFIG.SITE_DESCRIPTION }}">
{% endblock head %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="text-primary">Stats</h3>
    </div>
    <table class="table table-striped table-hover">
        <tr>
            <td>Books</td>
            <td>: {{ stats.books }}</td>
        </tr>
        <tr>
            <td>Book Copies</td>
            <td>: {{ stats.book_copies }}</td>
        </tr>
        <tr>
            <td>Periodicals</td>
            <td>: {{ stats.periodicals }}</td>
        </tr>
        <tr>
            <td>Periodical Issues</td>
            <td>: {{ stats.periodical_issues }}</td>
        </tr>
        <tr>
            <td>Categories</td>
            <td>: {{ stats.categories }}</td>
        </tr>
        <tr>
            <td>Languages</td>
            <td>: {{ stats.languages }}</td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block sidebar %}
{% if user.is_staff %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Quick Links</h4>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'circulations:add_circulation' %}">Issue Book</a></li>
        <li class="list-group-item"><a href="{% url 'circulations:return_circulation' %}">Return Book</a></li>
        <li class="list-group-item"><a href="{% url 'items:add_book_detail' %}">Add Book</a></li>
        <li class="list-group-item"><a href="{% url 'items:add_periodical' %}">Add Periodical</a></li>
        <li class="list-group-item"><a href="{% url 'items:add_category' %}">Add Category</a></li>
        <li class="list-group-item"><a href="{% url 'items:add_language' %}">Add Language</a></li>
    </ul>
</div>
{% endif %}
{% endblock sidebar %}